
#spring.data.mongodb.uri=mongodb+srv://ajeetsinghrawat1999_db_user:nHD9GyHvhfEmlqC2@cluster0.ov8rxni.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#server.port=8081
#server.servlet.context-path=/journal

#spring.data.mongodb.username=your_user_name
#spring.data.mongodb.password=your_password


